services:
  backend:
    build:
      context: .
      dockerfile: BackendDockerFile
    container_name: family-vault-backend
    ports:
      - "8080:8080"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: family-vault-frontend
    ports:
      - "3000:3000"
